name: utf_convert
version: 0.10.0+1

description: Provides common operations for manipulating Unicode sequences
homepage: https://github.com/DenchikBY/utf

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
